### ISSUE TITLE
Enumeration of available cameras.

### ISSUE THREAD

**Issue by trickeydan** [RealOrangeOne/zoloto#33]
It would be really useful to support enumeration of available cameras.

**Comment by RealOrangeOne** [comment]
If there's a simple implementation of this, i'd be open to adding it. Although if the implementation is too complex / weird, it might be one which has to be implemented by the user. 

Will give it a research, though!

**Comment by RealOrangeOne** [comment]
Unfortunately, there's no cross-platform way to enumerate devices, which is annoying. It's highly dependent on the backend.

However, brute forcing the id should work for this (and is actually how the V4L backend detects some cameras). 

Because it's important to get this right, It think it's ok to do this inside Zoloto.

Unfortunately, opencv prints every time it finds a bad camera, which is annoying. A patch has been pushed upstream https://github.com/opencv/opencv/pull/15111
